# Automagically generated by YAPar (M3)
import sys

# Importamos tu lexer generado en la fase M2
try:
    from thelexer import get_tokens
except ImportError:
    # Fallback dummy si thelexer.py no se encuentra en la misma ruta
    def get_tokens(text):
        for char in text.split():
            yield ('TOKEN', char)
        yield ('$', '$')

class ParserSLR1:
    def __init__(self):
        self.action = [
            {
                "c": "S1",
                "d": "S2"
            },
            {
                "c": "S1",
                "d": "S2"
            },
            {
                "c": "R3",
                "d": "R3",
                "$": "R3"
            },
            {
                "$": "ACC"
            },
            {
                "c": "S1",
                "d": "S2"
            },
            {
                "c": "R2",
                "d": "R2",
                "$": "R2"
            },
            {
                "$": "R1"
            }
        ]
        self.goto = [
            {
                "S": 3,
                "C": 4
            },
            {
                "C": 5
            },
            {},
            {},
            {
                "C": 6
            },
            {},
            {}
        ]
        self.productions = [
            {
                "head": "S'",
                "len": 1
            },
            {
                "head": "S",
                "len": 2
            },
            {
                "head": "C",
                "len": 2
            },
            {
                "head": "C",
                "len": 1
            }
        ]
        self.start_symbol = "S'"

    def parse(self, tokens_generator):
        stack = [0]
        lookahead = next(tokens_generator, None)

        def get_token_type(tok):
            if tok is None: return '$'
            # Adaptalo a la estructura que devuelva thelexer (ej. tok[1] o tok.type)
            if isinstance(tok, tuple):
                return tok[1] 
            return tok

        while True:
            state = stack[-1]
            a = get_token_type(lookahead)

            action = self.action[state].get(a)
            
            if action is None:
                print(f"Error sintactico en estado {state} con token '{a}'")
                return False

            if action.startswith('S'):
                # Shift
                stack.append(lookahead)
                stack.append(int(action[1:]))
                print(f"Shift a estado {action[1:]} con token {a}")
                lookahead = next(tokens_generator, None)
            
            elif action.startswith('R'):
                # Reduce
                prod_idx = int(action[1:])
                prod = self.productions[prod_idx]
                
                # Pop 2 * len(beta) de la pila
                for _ in range(2 * prod["len"]):
                    stack.pop()
                
                top_state = stack[-1]
                new_state = self.goto[top_state].get(prod["head"])
                
                stack.append(prod["head"])
                stack.append(new_state)
                print(f"Reduce por {prod['head']} -> longitud {prod['len']} (GOTO {new_state})")
            
            elif action == 'ACC':
                print("Analisis exitoso (ACC) - Cadena Aceptada")
                return True
            else:
                print("Accion desconocida")
                return False

if __name__ == "__main__":
    # Prueba del algoritmo Shift-Reduce
    test_input = "c d d" # Cambiar segun gramatica de prueba
    print(f"Parseando cadena: {test_input}")
    tokens = get_tokens(test_input)
    parser = ParserSLR1()
    parser.parse(tokens)