/**
 * ParserGenerator.js
 * 
 * Módulo principal que orquesta la generación del analizador sintáctico.
 * 
 * Responsabilidades:
 * 1. A partir del Autómata LR(0), construir las tablas ACTION y GOTO.
 * 2. Detectar conflictos Shift/Reduce y Reduce/Reduce.
 * 3. Emitir el código Python final (parser.py) inyectando las tablas 
 *    e importando el lexer.py generado en la fase anterior.
 * 
 * Estado: En diseño (Arquitectura)
 */

class ParserGenerator {
    constructor(automaton, grammar, sets) {
        this.automaton = automaton;
        this.grammar = grammar;
        this.sets = sets;
        this.actionTable = [];
        this.gotoTable = [];
        this.conflicts = [];
    }

    /**
     * Construye las tablas ACTION y GOTO para el parser SLR(1)
     */
    buildTables() {
        const { states, transitions } = this.automaton.getAutomaton();

        // Inicializar tablas
        states.forEach(() => {
            this.actionTable.push({});
            this.gotoTable.push({});
        });

        // 1. Procesar transiciones (Shift y Goto)
        transitions.forEach(t => {
            if (this.grammar.terminals.includes(t.symbol)) {
                this.actionTable[t.from][t.symbol] = 'S' + t.to;
            } else if (this.grammar.nonTerminals.includes(t.symbol)) {
                this.gotoTable[t.from][t.symbol] = t.to;
            }
        });

        // 2. Procesar reducciones (Reduce y Accept)
        states.forEach((stateItems, i) => {
            stateItems.forEach(item => {
                const prod = this.grammar.productions[item.prodIndex];
                
                // Si el punto está al final (A -> alpha .)
                if (item.dotPos === prod.body.length || (prod.body.length === 1 && prod.body[0] === 'epsilon')) {
                    if (prod.head === this.grammar.startSymbol) {
                        this.actionTable[i]['$'] = 'ACC';
                    } else {
                        const followA = this.sets.follow.get(prod.head);
                        if (followA) {
                            followA.forEach(term => {
                                const existing = this.actionTable[i][term];
                                if (existing && existing !== 'R' + item.prodIndex) {
                                    this.conflicts.push(`Conflict at state ${i} on '${term}': ${existing} vs R${item.prodIndex}`);
                                } else {
                                    this.actionTable[i][term] = 'R' + item.prodIndex;
                                }
                            });
                        }
                    }
                }
            });
        });
    }

    getTables() {
        return {
            action: this.actionTable,
            goto: this.gotoTable,
            conflicts: this.conflicts
        };
    }

    // Emite el archivo parser.py con el algoritmo Shift-Reduce embebido
    generateParserFile(outputPath) {
        const fs = require('fs');
        const actionTableStr = JSON.stringify(this.actionTable, null, 4);
        const gotoTableStr = JSON.stringify(this.gotoTable, null, 4);
        
        // Mapeamos las producciones (solo necesitamos la cabecera y la longitud de la regla para el pop)
        const productions = this.grammar.productions.map(p => ({
            head: p.head,
            len: (p.body.length === 1 && p.body[0] === 'epsilon') ? 0 : p.body.length
        }));
        const productionsStr = JSON.stringify(productions, null, 4);
        const startSymbol = this.grammar.startSymbol;

        const pythonCode = `
# Automagically generated by YAPar (M3)
import sys

# Importamos tu lexer generado en la fase M2
try:
    from thelexer import get_tokens
except ImportError:
    # Fallback dummy si thelexer.py no se encuentra en la misma ruta
    def get_tokens(text):
        for char in text.split():
            yield ('TOKEN', char)
        yield ('$', '$')

class ParserSLR1:
    def __init__(self):
        self.action = ${actionTableStr.replace(/\n/g, '\n        ')}
        self.goto = ${gotoTableStr.replace(/\n/g, '\n        ')}
        self.productions = ${productionsStr.replace(/\n/g, '\n        ')}
        self.start_symbol = "${startSymbol}"

    def parse(self, tokens_generator):
        stack = [0]
        lookahead = next(tokens_generator, None)

        def get_token_type(tok):
            if tok is None: return '$'
            # Adaptalo a la estructura que devuelva thelexer (ej. tok[1] o tok.type)
            if isinstance(tok, tuple):
                return tok[1] 
            return tok

        while True:
            state = stack[-1]
            a = get_token_type(lookahead)

            action = self.action[state].get(a)
            
            if action is None:
                print(f"Error sintactico en estado {state} con token '{a}'")
                return False

            if action.startswith('S'):
                # Shift
                stack.append(lookahead)
                stack.append(int(action[1:]))
                print(f"Shift a estado {action[1:]} con token {a}")
                lookahead = next(tokens_generator, None)
            
            elif action.startswith('R'):
                # Reduce
                prod_idx = int(action[1:])
                prod = self.productions[prod_idx]
                
                # Pop 2 * len(beta) de la pila
                for _ in range(2 * prod["len"]):
                    stack.pop()
                
                top_state = stack[-1]
                new_state = self.goto[top_state].get(prod["head"])
                
                stack.append(prod["head"])
                stack.append(new_state)
                print(f"Reduce por {prod['head']} -> longitud {prod['len']} (GOTO {new_state})")
            
            elif action == 'ACC':
                print("Analisis exitoso (ACC) - Cadena Aceptada")
                return True
            else:
                print("Accion desconocida")
                return False

if __name__ == "__main__":
    # Prueba del algoritmo Shift-Reduce
    test_input = "c d d" # Cambiar segun gramatica de prueba
    print(f"Parseando cadena: {test_input}")
    tokens = get_tokens(test_input)
    parser = ParserSLR1()
    parser.parse(tokens)
`;
        fs.writeFileSync(outputPath, pythonCode.trim());
        console.log(`\nArchivo de parser generado exitosamente en: ${outputPath}`);
    }
}

module.exports = ParserGenerator;
